site_name: KD Lavalink
site_author: ErrorDoc404
site_url: https://kdlavalink.cf
repo_name: 'kdlavalink.cf'
repo_url: 'https://github.com/ErrorDoc404/kdlavalink'

theme:
  name: material
  palette:
    -media: "light"
    schema: default
    primary: 'lime'
    accent: "tale"

# theme:
#   name: material
#   include_search_page: false
#   search_index_only: true
#   palette:
#     - media: "light"
#       scheme: default
#       primary: 'lime'
#       accent: 'teal'
#       toggle:
#         icon: material/weather-night
#         name: Switch to dark mode
#     - media: "dark"
#       scheme: slate
#       toggle:
#         icon: material/weather-sunny
#         name: Switch to light mode
#   features:
#     - tabs
#     - instantsite
#     - navigation.tracking
#     - navigation.expand
#     - content.code.annotate
#     - navigation.indexes
#     - navigation.instant
#     - navigation.sections
#     - navigation.top
#     - search.highlight
#     - search.suggest

plugins:
  - search
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  #       conventions.md: philosophy.md
  #       reference/meta-tags.md: reference/index.md
  #       reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
  #       sponsorship.md: insiders/index.md
  #       upgrading.md: upgrade.md
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: index.md
    - Lavalink SSL: ssl.md
    - Lavalink without SSL: non-ssl.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false

copyright: 'Copyright &copy; 2022 kartadharta.cf'
